changelog:
  categories:
  - title: Breaking Changes
    labels:
    - breaking
  - title: Features
    labels:
    - feat
  - title: Bug Fixes
    labels:
    - fix
  - title: Documentation
    labels:
    - docs
  - title: Maintenance
    labels:
    - chore
    - refactor
    - ci
    - build
    - test
  - title: Other Changes
    labels:
    - '*'
  exclude:
    labels:
    - ignore-for-release
