name: pre-commit

on:
  push:
    branches:
    - main
  merge_group:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0   # v7.0.0
      with:
        fetch-depth: 0
        token: ${{ secrets.LEMBAS_BOT_TOKEN || github.token }}

    - name: Set up pixi
      uses: prefix-dev/setup-pixi@5185adfbffb4bd703da3010310260805d89ebb11 # v0.9.6
      with:
        pixi-version: v0.44.0
        locked: false

    - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae   # v5.0.5
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ runner.arch }}-${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Run pre-commit
      id: updates
      run: |
        pixi run pre-commit-run || :
        if git status --porcelain | grep -q .; then
          echo "changed=1" >> "${GITHUB_OUTPUT}"
        fi

    - name: Commit and fail if changes occurred
      if: steps.updates.outputs.changed == 1
      env:
        REF: ${{ github.head_ref }}
      run: |
        git fetch origin "refs/heads/${REF}:refs/remotes/origin/${REF}"
        git checkout "${REF}"

        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add -u
        git commit -m "chore(pre-commit): auto-fix"
        git push

        echo "::error::Changes were committed. A new CI run will start."
        exit 1
