name: Run Tests

on:
  push:
    branches:
    - main
    tags:
    - v[0-9]+.[0-9]+.[0-9]+*
  pull_request:
  merge_group:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11", "3.12", "3.13"]
        include:
        - python-version: "3.14"
          os: ubuntu-latest
          experimental: true
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out repository
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10   # v6.0.3
    - name: Set up python ${{ matrix.python-version }}
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1   # v6.3.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install library
      run: pip install ".[ci]"
    - name: Static type checking
      run: mypy
    - name: Test with pytest
      run: |
        pytest \
          --junitxml=./test-reports/junit.xml \
          --cov-report xml:./test-reports/coverage.xml \
          --cov lembas \
          --cov tests \
          tests
    - name: Publish code coverage
      uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f   # v7.0.0
      with:
        files: ./test-reports/coverage.xml
        env_vars: OS,PYTHON
  build:
    uses: ./.github/workflows/build.yml

  # This check job runs to ensure all tests and builds have passed, such that we can use it as a "wildcard"
  # for branch protection to ensure all tests pass before a PR can be merged.
  check:
    if: always()
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
    - name: Decide whether all required jobs succeeded or failed
      uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # release/v1
      with:
        jobs: ${{ toJSON(needs) }}

  publish:
    uses: ./.github/workflows/publish.yml
    needs: [check]
    secrets: inherit
    if: ${{ github.ref == 'refs/heads/main' || startsWith(github.event.ref, 'refs/tags/v') }}
